name: Actions develop >>>>> Pull Request
on: 
  push:
    branches:
      # - '*'
      # - '!master'
      # - '!develop'
      - 'feature/**'
      - 'bugfix/**'

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    name: Create branches for Pull Request
    steps:
      - name: Set output 
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - run: echo "🎉 El evento se ejecutó en la rama ${{ steps.vars.outputs.short_ref }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get current time action
        uses: gerred/actions/current-time@master
        id: current-time

      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: '${{ steps.vars.outputs.short_ref }}'

      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: '${{ steps.string.outputs.uppercase }}'
          split-by: '/'


      - name: Create Pull Request
        uses: shubhsherl/create-catchup-pr@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{github.repository}}

          SOURCE_BRANCH: "${{ steps.vars.outputs.short_ref }}"
          TARGET_BRANCH: "develop"
          TITLE: '[Pull request - ${{ github.actor }}] Into develop from ${{ steps.vars.outputs.short_ref }}'
          BODY: | 
            ${{ steps.split.outputs._0 == 'BUGFIX' && '🟥 BUGFIX' || '🟩 FEATURE' }}
            🔷 Actor: ${{ github.actor }}
            🔷 Source: ${{ steps.vars.outputs.short_ref }}
            🔷 Dated: ${{ steps.current-time.outputs.time }}
            🔷 Auto-generated by [create-pull-request][1]
            
            [1]: https://github.com/InterfazProductosDigitales     